### ISSUE TITLE
Additional Attributes in Character Sheet

### ISSUE THREAD

**Issue by Muji-k** [xdy/twodsix-foundryvtt#527] opened 2021-06-19 12:18 UTC
If possible, add the ability to display additional attributes in the character sheet so we can include the optional characteristics from mongoose traveller companion 2nd edition: (Wealth (WLT), Lucky (LCK), Morale (MRL), Sanity (STY)).
Maybe this could bi included in the form of a system option, where you can toggle the display of the new attributes on or off.

**Comment by xdy** [comment] 2021-06-21 17:26
Unfortunately we can't support those attributes as they are not available under the OGL.
We *could* however support allowing the user to enter new attributes, giving them whatever name and abbreviations they want.
As long as we can figure out how to fit those extra characteristics onto the character sheet. :)

Anway, closing this as a duplicate of https://github.com/xdy/twodsix-foundryvtt/issues/189

**Closed by xdy** 2021-06-21 17:26 UTC
