### ISSUE TITLE
Equipment & Tool section in inventory does not show any items

### ISSUE THREAD

**Issue by Madventurer** [xdy/twodsix-foundryvtt#1190] opened 2022-12-01 11:58 UTC
After 2.11.1, the inventory section merged for Equipment and Tools does not show any items added whatsoever. This was already an issue for Tools in previous version.

1. Go to an actor's inventory
2. Click on Add Item (Equipment by default, try changing an item from a weapon to equipment/tool too)
3. Item does not appear. However, it is added to the sheet, simply not displayed anywhere.

**Comment by marvin9257** [comment] 2022-12-01 13:00
I can't reproduce this problem.  Are you adding an item using the "+" on the actor sheet or adding an item to the game item list using the "Create Item" button?  If the latter, that only creates an item in the game item list.  You need to drag it onto the actor to "attach" it.

**Comment by marvin9257** [comment] 2023-02-18 17:38
I'm closing this issue as I can't reproduce it or had a response to the above questions.

**Closed by marvin9257** 2023-02-18 17:38 UTC
